name: "fill-jira-ticket"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test
    - uses: ./
      with:
        milliseconds: 1000
